Sprint 25 odim 3258
shivacharanms/ODIM pull request #10
Opened 2020-09-08 08:28 UTC by shivacharanms

This PR contains the SimpleUpdate action implementation under UpdateService

2020-09-08 08:37 UTC, jeevan-kamkar reviewed
please remove the commented code

2020-09-08 08:37 UTC, jeevan-kamkar commented on svc-update/update/simpleUpdate.go
> +		//contactRequest.PostBody = updateRequest
remove the commented line

2020-09-08 08:42 UTC, bharath-b-hpe approved these changes

2020-09-08 08:52 UTC, a-ajith approved these changes

2020-09-08 08:55 UTC, skhan-anjum approved these changes

2020-09-08 09:02 UTC, jeevan-kamkar approved these changes
LGTM

2020-09-09 06:09 UTC, jeevan-kamkar requested changes
Address the requested changes

2020-09-09 06:09 UTC, jeevan-kamkar commented on svc-update/update/simpleUpdate.go
> +		replaceTargetUUID := strings.Replace(string(req.RequestBody), uuid+":", "", -1)
the request which is sent to plugin needs to /ODIM  resource links instead of /redfish/ please update the same

2020-09-09 07:56 UTC, jeevan-kamkar approved these changes
LGTM

2020-09-09 07:59 UTC, merged