UpdateService actions: simple update implemewntation on GRF plugin
shivacharanms/ODIM pull request #9
Opened 2020-09-07 12:46 UTC by shivacharanms

SimpleUpdate action implementation on the GRF plugin side.

2020-09-08 04:10 UTC, jeevan-kamkar approved these changes
LGTM

2020-09-09 06:12 UTC, jeevan-kamkar requested changes
Address the requested changes

2020-09-09 06:12 UTC, jeevan-kamkar commented on plugin-redfish/rfphandler/update.go
> +	device := &rfputilities.RedfishDevice{
before sending the request to the device replace /ODIM/ with /redfish

2020-09-09 07:41 UTC, a-ajith approved these changes

2020-09-09 07:44 UTC, irappa-pattar commented on plugin-redfish/rfphandler/update.go
> +	resp, err := redfishClient.DeviceCall(device, uri, "POST")
instead of "POST" use http.MethodPost

2020-09-09 07:44 UTC, irappa-pattar commented on plugin-redfish/rfphandler/update_test.go
> +	test.POST("/ODIM/v1/UpdateService/Actions.SimpleUpdate").WithJSON(requestBody).Expect().Status(http.StatusOK)
No negative test cases

2020-09-09 07:52 UTC, shivacharanms commented on plugin-redfish/rfphandler/update_test.go
> +	test.POST("/ODIM/v1/UpdateService/Actions.SimpleUpdate").WithJSON(requestBody).Expect().Status(http.StatusOK)
Since ilo handles response body validation, I cannot have negative scenarios here

2020-09-09 07:53 UTC, shivacharanms commented on plugin-redfish/rfphandler/update.go
> +	resp, err := redfishClient.DeviceCall(device, uri, "POST")
Done

2020-09-09 07:54 UTC, irappa-pattar approved these changes

2020-09-09 08:00 UTC, bharath-b-hpe approved these changes

2020-09-09 08:01 UTC, merged